/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class four_non_bronds_yyys_zzztimer_util_DTFM */

#ifndef _Included_four_non_bronds_yyys_zzztimer_util_DTFM
#define _Included_four_non_bronds_yyys_zzztimer_util_DTFM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     four_non_bronds_yyys_zzztimer_util_DTFM
 * Method:    initDefaultChanel
 * Signature: (Lfour/non/bronds/yyys/zzztimer/util/DTFM;)V
 */
JNIEXPORT void JNICALL Java_four_non_bronds_yyys_zzztimer_util_DTFM_initDefaultChanel
  (JNIEnv *, jclass, jobject);

/*
 * Class:     four_non_bronds_yyys_zzztimer_util_DTFM
 * Method:    resetChanel
 * Signature: (Lfour/non/bronds/yyys/zzztimer/util/DTFM;)V
 */
JNIEXPORT void JNICALL Java_four_non_bronds_yyys_zzztimer_util_DTFM_resetChanel
  (JNIEnv *, jclass, jobject);

/*
 * Class:     four_non_bronds_yyys_zzztimer_util_DTFM
 * Method:    destroyDefaultChanel
 * Signature: (Lfour/non/bronds/yyys/zzztimer/util/DTFM;)V
 */
JNIEXPORT void JNICALL Java_four_non_bronds_yyys_zzztimer_util_DTFM_destroyDefaultChanel
  (JNIEnv *, jclass, jobject);

/*
 * Class:     four_non_bronds_yyys_zzztimer_util_DTFM
 * Method:    getSampleBitPerSec
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_four_non_bronds_yyys_zzztimer_util_DTFM_getSampleBitPerSec
  (JNIEnv *, jclass, jlong);

/*
 * Class:     four_non_bronds_yyys_zzztimer_util_DTFM
 * Method:    setSampleBitPerSec
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_four_non_bronds_yyys_zzztimer_util_DTFM_setSampleBitPerSec
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     four_non_bronds_yyys_zzztimer_util_DTFM
 * Method:    getSampleBits
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_four_non_bronds_yyys_zzztimer_util_DTFM_getSampleBits
  (JNIEnv *, jclass, jlong);

/*
 * Class:     four_non_bronds_yyys_zzztimer_util_DTFM
 * Method:    setSampleBits
 * Signature: (JS)V
 */
JNIEXPORT void JNICALL Java_four_non_bronds_yyys_zzztimer_util_DTFM_setSampleBits
  (JNIEnv *, jclass, jlong, jshort);

/*
 * Class:     four_non_bronds_yyys_zzztimer_util_DTFM
 * Method:    getChanel
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_four_non_bronds_yyys_zzztimer_util_DTFM_getChanel
  (JNIEnv *, jclass, jlong);

/*
 * Class:     four_non_bronds_yyys_zzztimer_util_DTFM
 * Method:    setChanel
 * Signature: (JS)V
 */
JNIEXPORT void JNICALL Java_four_non_bronds_yyys_zzztimer_util_DTFM_setChanel
  (JNIEnv *, jclass, jlong, jshort);

/*
 * Class:     four_non_bronds_yyys_zzztimer_util_DTFM
 * Method:    getSingnalMsec
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_four_non_bronds_yyys_zzztimer_util_DTFM_getSingnalMsec
  (JNIEnv *, jclass, jlong);

/*
 * Class:     four_non_bronds_yyys_zzztimer_util_DTFM
 * Method:    setSingnalMsec
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_four_non_bronds_yyys_zzztimer_util_DTFM_setSingnalMsec
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     four_non_bronds_yyys_zzztimer_util_DTFM
 * Method:    getJudgeMsec
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_four_non_bronds_yyys_zzztimer_util_DTFM_getJudgeMsec
  (JNIEnv *, jclass, jlong);

/*
 * Class:     four_non_bronds_yyys_zzztimer_util_DTFM
 * Method:    setJudgeMsec
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_four_non_bronds_yyys_zzztimer_util_DTFM_setJudgeMsec
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     four_non_bronds_yyys_zzztimer_util_DTFM
 * Method:    getBlankMsec
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_four_non_bronds_yyys_zzztimer_util_DTFM_getBlankMsec
  (JNIEnv *, jclass, jlong);

/*
 * Class:     four_non_bronds_yyys_zzztimer_util_DTFM
 * Method:    setBlankMsec
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_four_non_bronds_yyys_zzztimer_util_DTFM_setBlankMsec
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     four_non_bronds_yyys_zzztimer_util_DTFM
 * Method:    getWaveFileHeader
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_four_non_bronds_yyys_zzztimer_util_DTFM_getWaveFileHeader
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     four_non_bronds_yyys_zzztimer_util_DTFM
 * Method:    updateWaveFileHeaderFile
 * Signature: (JILjava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_four_non_bronds_yyys_zzztimer_util_DTFM_updateWaveFileHeaderFile
  (JNIEnv *, jclass, jlong, jint, jstring, jobjectArray);

/*
 * Class:     four_non_bronds_yyys_zzztimer_util_DTFM
 * Method:    string2PCM
 * Signature: (JLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_four_non_bronds_yyys_zzztimer_util_DTFM_string2PCM
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     four_non_bronds_yyys_zzztimer_util_DTFM
 * Method:    analyzeDTFMFile
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_four_non_bronds_yyys_zzztimer_util_DTFM_analyzeDTFMFile
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     four_non_bronds_yyys_zzztimer_util_DTFM
 * Method:    analyzeDTFMBuffring
 * Signature: (J[BILfour/non/bronds/yyys/zzztimer/util/PCMRecordBuffring;)V
 */
JNIEXPORT void JNICALL Java_four_non_bronds_yyys_zzztimer_util_DTFM_analyzeDTFMBuffring
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jobject);

/*
 * Class:     four_non_bronds_yyys_zzztimer_util_DTFM
 * Method:    nEncExtString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_four_non_bronds_yyys_zzztimer_util_DTFM_nEncExtString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     four_non_bronds_yyys_zzztimer_util_DTFM
 * Method:    nDecExtString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_four_non_bronds_yyys_zzztimer_util_DTFM_nDecExtString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     four_non_bronds_yyys_zzztimer_util_DTFM
 * Method:    openWriteOgg
 * Signature: (JLjava/lang/String;[Lfour/non/bronds/yyys/zzztimer/bean/MusicTagBean;)Z
 */
JNIEXPORT jboolean JNICALL Java_four_non_bronds_yyys_zzztimer_util_DTFM_openWriteOgg
  (JNIEnv *, jclass, jlong, jstring, jobjectArray);

/*
 * Class:     four_non_bronds_yyys_zzztimer_util_DTFM
 * Method:    closeWriteOgg
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_four_non_bronds_yyys_zzztimer_util_DTFM_closeWriteOgg
  (JNIEnv *, jclass, jlong);

/*
 * Class:     four_non_bronds_yyys_zzztimer_util_DTFM
 * Method:    writeOgg
 * Signature: (J[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_four_non_bronds_yyys_zzztimer_util_DTFM_writeOgg
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     four_non_bronds_yyys_zzztimer_util_DTFM
 * Method:    convertOgg
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_four_non_bronds_yyys_zzztimer_util_DTFM_convertOgg
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
